export interface SoundEffect {
  id: string;
  name: string;
  description: string;
  category: SoundCategory;
  tags: string[];
  duration: number; // in seconds
  audioUrl: string;
  waveform: number[]; // Values between 0-1 representing the waveform
  createdAt: string;
  featured: boolean;
  downloads: number;
}

export type SoundCategory =
  | "Hover"
  | "Notifications"
  | "Transitions"
  | "Click"
  | "Error"
  | "Loading"
  | "Confirmation"
  | "Feedback"
  | "Pop"
  | "Alert"
  | "Typing"
  | "Navigation";

export const ALL_CATEGORIES: SoundCategory[] = [
  "Click",
  "Notifications",
  "Feedback",
  "Transitions",
  "Hover",
  "Confirmation",
  "Error",
  "Loading",
  "Pop",
  "Alert",
  "Typing",
  "Navigation",
];

export const mockSoundEffects: SoundEffect[] = [
  {
    id: "click-1",
    name: "Cosmic Ping Resonance",
    description:
      "An ethereal ping sound that echoes through digital space, perfect for space-themed interfaces",
    category: "Click",
    tags: ["space", "ethereal", "ping", "futuristic", "cosmic"],
    duration: 0.8,
    audioUrl: "/sounds/simple_click_button_1.mp3",
    waveform: [0.2, 0.5, 0.8, 0.6, 0.4, 0.3, 0.2, 0.1],
    createdAt: "2025-04-15",
    featured: true,
    downloads: 4521,
  },
  {
    id: "click-2",
    name: "Crystal Chime Cascade",
    description:
      "A delicate crystalline sound that creates an atmosphere of elegance and precision",
    category: "Click",
    tags: ["crystal", "elegant", "chime", "magical", "clear"],
    duration: 0.8,
    audioUrl: "/sounds/Click_1.mp3",
    waveform: [0.2, 0.5, 0.8, 0.6, 0.4, 0.3, 0.2, 0.1],
    createdAt: "2025-05-03",
    featured: true,
    downloads: 2876,
  },
  {
    id: "click-3",
    name: "Quantum Tech Pulse",
    description:
      "A modern, tech-inspired pulse that suggests advanced processing and computational power",
    category: "Click",
    tags: ["tech", "quantum", "pulse", "modern", "processing"],
    duration: 0.8,
    audioUrl: "/sounds/Click_3.mp3",
    waveform: [0.2, 0.5, 0.8, 0.6, 0.4, 0.3, 0.2, 0.1],
    createdAt: "2025-06-21",
    featured: true,
    downloads: 7234,
  },
  {
    id: "click-4",
    name: "Forest Whisper Alert",
    description:
      "A gentle, nature-inspired notification that brings a touch of organic calm to digital interfaces",
    category: "Click",
    tags: ["nature", "organic", "gentle", "calming", "forest"],
    duration: 0.8,
    audioUrl: "/sounds/Click_4.mp3",
    waveform: [0.2, 0.5, 0.8, 0.6, 0.4, 0.3, 0.2, 0.1],
    createdAt: "2025-07-08",
    featured: true,
    downloads: 1543,
  },
  {
    id: "click-5",
    name: "Retro Gaming Blip",
    description:
      "A nostalgic 8-bit style sound effect that evokes classic gaming experiences",
    category: "Click",
    tags: ["retro", "gaming", "8-bit", "nostalgic", "arcade"],
    duration: 0.8,
    audioUrl: "/sounds/Click_5.mp3",
    waveform: [0.2, 0.5, 0.8, 0.6, 0.4, 0.3, 0.2, 0.1],
    createdAt: "2025-08-15",
    featured: true,
    downloads: 9876,
  },
  {
    id: "click-6",
    name: "Mechanical Keyboard Click",
    description:
      "A satisfying mechanical keyboard sound that provides tactile audio feedback",
    category: "Click",
    tags: ["mechanical", "keyboard", "tactile", "click", "feedback"],
    duration: 0.8,
    audioUrl: "/sounds/Click_6.mp3",
    waveform: [0.2, 0.5, 0.8, 0.6, 0.4, 0.3, 0.2, 0.1],
    createdAt: "2025-09-02",
    featured: true,
    downloads: 3421,
  },
  {
    id: "click-7",
    name: "Liquid Drop Transition",
    description:
      "A smooth, liquid-inspired transition sound that flows naturally between states",
    category: "Click",
    tags: ["liquid", "smooth", "transition", "flow", "water"],
    duration: 0.8,
    audioUrl: "/sounds/Click_7.mp3",
    waveform: [0.2, 0.5, 0.8, 0.6, 0.4, 0.3, 0.2, 0.1],
    createdAt: "2025-10-19",
    featured: true,
    downloads: 6543,
  },
  {
    id: "click-8",
    name: "Neon Hover Glow",
    description:
      "A bright, energetic hover sound that matches neon-styled UI elements",
    category: "Click",
    tags: ["neon", "bright", "energetic", "synthetic", "hover"],
    duration: 0.8,
    audioUrl: "/sounds/Click_8.mp3",
    waveform: [0.2, 0.5, 0.8, 0.6, 0.4, 0.3, 0.2, 0.1],
    createdAt: "2025-11-05",
    featured: true,
    downloads: 5432,
  },
  {
    id: "confirmation-1",
    name: "Digital Success Chime",
    description:
      "A modern, digital chime that signals successful completion of tasks",
    category: "Confirmation",
    tags: ["success", "digital", "chime", "completion", "modern"],
    duration: 1.5,
    audioUrl: "/sounds/Confirmation_1.mp3",
    waveform: [0.1, 0.3, 0.5, 0.7, 0.9, 0.7, 0.5, 0.3, 0.1],
    createdAt: "2025-04-20",
    featured: true,
    downloads: 3892,
  },
  {
    id: "confirmation-2",
    name: "Ambient Space Hum",
    description:
      "A deep, resonant ambient sound that creates an immersive atmosphere",
    category: "Confirmation",
    tags: ["ambient", "space", "deep", "resonant", "atmosphere"],
    duration: 4.0,
    audioUrl: "/sounds/Confirmation_2.mp3",
    waveform: [0.3, 0.4, 0.5, 0.4, 0.3, 0.4, 0.5, 0.6, 0.5, 0.4, 0.3],
    createdAt: "2025-05-15",
    featured: true,
    downloads: 2765,
  },
  {
    id: "confirmation-3",
    name: "Zen Garden Chime",
    description:
      "A peaceful, meditative sound inspired by traditional Japanese gardens",
    category: "Confirmation",
    tags: ["zen", "peaceful", "meditation", "garden", "calm"],
    duration: 4.0,
    audioUrl: "/sounds/Confirmation_3.mp3",
    waveform: [0.3, 0.4, 0.5, 0.4, 0.3, 0.4, 0.5, 0.6, 0.5, 0.4, 0.3],
    createdAt: "2025-06-10",
    featured: true,
    downloads: 1892,
  },
  {
    id: "confirmation-4",
    name: "Quantum Success Tone",
    description:
      "A futuristic success sound that combines digital and organic elements",
    category: "Confirmation",
    tags: ["quantum", "futuristic", "success", "digital", "organic"],
    duration: 4.0,
    audioUrl: "/sounds/Confirmation_4.mp3",
    waveform: [0.3, 0.4, 0.5, 0.4, 0.3, 0.4, 0.5, 0.6, 0.5, 0.4, 0.3],
    createdAt: "2025-07-25",
    featured: true,
    downloads: 4321,
  },
  {
    id: "error-1",
    name: "Digital Warning Alert",
    description:
      "A clear, attention-grabbing warning sound for critical notifications",
    category: "Error",
    tags: ["warning", "alert", "critical", "digital", "attention"],
    duration: 1.2,
    audioUrl: "/sounds/Error_Tone_1.mp3",
    waveform: [0.5, 0.8, 0.3, 0.7, 0.4, 0.6, 0.2],
    createdAt: "2025-08-05",
    featured: false,
    downloads: 2987,
  },
  {
    id: "error-2",
    name: "System Error Pulse",
    description: "A pulsing error sound that indicates system-level issues",
    category: "Error",
    tags: ["system", "error", "pulse", "technical", "alert"],
    duration: 1.2,
    audioUrl: "/sounds/Error_Tone_2.mp3",
    waveform: [0.3, 0.6, 0.9, 0.7, 0.5, 0.3, 0.1],
    createdAt: "2025-09-18",
    featured: false,
    downloads: 3456,
  },
  {
    id: "error-3",
    name: "Critical Alert Tone",
    description: "An urgent alert sound for critical system notifications",
    category: "Error",
    tags: ["critical", "urgent", "alert", "system", "warning"],
    duration: 1.1,
    audioUrl: "/sounds/Error_Tone_3.mp3",
    waveform: [0.1, 0.2, 0.4, 0.6, 0.8, 0.6, 0.4, 0.2, 0.1],
    createdAt: "2025-10-30",
    featured: true,
    downloads: 4123,
  },
  {
    id: "feedback-1",
    name: "Processing Loop",
    description:
      "A smooth, continuous loop sound for background processing states",
    category: "Feedback",
    tags: ["processing", "loop", "background", "smooth", "continuous"],
    duration: 2.5,
    audioUrl: "/sounds/Feedback_1.mp3",
    waveform: [0.2, 0.4, 0.6, 0.5, 0.3, 0.5, 0.7, 0.6, 0.4, 0.2],
    createdAt: "2025-11-15",
    featured: false,
    downloads: 2876,
  },
  {
    id: "feedback-2",
    name: "Touch Response",
    description: "A subtle tactile feedback sound for touch interactions",
    category: "Feedback",
    tags: ["touch", "tactile", "response", "subtle", "interaction"],
    duration: 0.5,
    audioUrl: "/sounds/Feedback_2.mp3",
    waveform: [0.6, 0.8, 0.4, 0.2, 0.1],
    createdAt: "2025-04-25",
    featured: false,
    downloads: 1987,
  },
  {
    id: "feedback-3",
    name: "Message Notification",
    description: "A friendly notification sound for incoming messages",
    category: "Feedback",
    tags: ["message", "notification", "friendly", "alert", "social"],
    duration: 1.3,
    audioUrl: "/sounds/Feedback_3.mp3",
    waveform: [0.2, 0.5, 0.7, 0.9, 0.8, 0.6, 0.4, 0.2, 0.1],
    createdAt: "2025-05-30",
    featured: true,
    downloads: 3456,
  },
  {
    id: "feedback-4",
    name: "Interface Hover",
    description: "A subtle sound that enhances hover interactions",
    category: "Feedback",
    tags: ["hover", "interface", "subtle", "interaction", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Feedback_4.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-06-15",
    featured: true,
    downloads: 2345,
  },
  {
    id: "loading-1",
    name: "Progress Indicator",
    description: "A smooth, continuous sound for loading progress",
    category: "Loading",
    tags: ["progress", "loading", "continuous", "smooth", "indicator"],
    duration: 0.4,
    audioUrl: "/sounds/Loading_1.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-07-20",
    featured: false,
    downloads: 1876,
  },
  {
    id: "loading-2",
    name: "Loading Sequence",
    description: "A sequential loading sound that indicates progress",
    category: "Loading",
    tags: ["sequence", "loading", "progress", "steps", "indicator"],
    duration: 0.4,
    audioUrl: "/sounds/Loading_2.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-08-25",
    featured: false,
    downloads: 2134,
  },
  {
    id: "hover-1",
    name: "Menu Hover Effect",
    description: "A subtle sound for menu item hover interactions",
    category: "Hover",
    tags: ["menu", "hover", "subtle", "navigation", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Menu_UI_Hover_1.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-09-10",
    featured: false,
    downloads: 2987,
  },
  {
    id: "hover-2",
    name: "Button Hover",
    description: "A responsive hover sound for button interactions",
    category: "Hover",
    tags: ["button", "hover", "responsive", "interaction", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Menu_UI_Hover_2.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-10-15",
    featured: false,
    downloads: 3456,
  },
  {
    id: "hover-3",
    name: "Link Hover",
    description: "A subtle sound for link hover interactions",
    category: "Hover",
    tags: ["link", "hover", "subtle", "navigation", "web"],
    duration: 0.4,
    audioUrl: "/sounds/Menu_UI_Hover_3.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-11-20",
    featured: false,
    downloads: 2765,
  },
  {
    id: "hover-4",
    name: "Card Hover",
    description: "A smooth hover sound for card elements",
    category: "Hover",
    tags: ["card", "hover", "smooth", "UI", "interaction"],
    duration: 0.4,
    audioUrl: "/sounds/Menu_UI_Hover_4.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-12-05",
    featured: false,
    downloads: 1987,
  },
  {
    id: "notifications-1",
    name: "Alert Notification",
    description: "A clear, attention-grabbing notification sound",
    category: "Notifications",
    tags: ["alert", "notification", "attention", "clear", "important"],
    duration: 0.4,
    audioUrl: "/sounds/Notification_1.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-04-10",
    featured: false,
    downloads: 3456,
  },
  {
    id: "notifications-2",
    name: "Social Update",
    description: "A friendly notification for social media updates",
    category: "Notifications",
    tags: ["social", "update", "friendly", "notification", "media"],
    duration: 0.4,
    audioUrl: "/sounds/Notification_2.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-05-20",
    featured: false,
    downloads: 2987,
  },
  {
    id: "notifications-3",
    name: "System Update",
    description: "A professional notification for system updates",
    category: "Notifications",
    tags: ["system", "update", "professional", "notification", "technical"],
    duration: 0.4,
    audioUrl: "/sounds/Notification_3.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-06-30",
    featured: false,
    downloads: 2765,
  },
  {
    id: "notifications-4",
    name: "Email Alert",
    description: "A distinct notification for incoming emails",
    category: "Notifications",
    tags: ["email", "alert", "incoming", "mail", "notification"],
    duration: 0.4,
    audioUrl: "/sounds/Notification_4.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-07-15",
    featured: false,
    downloads: 4321,
  },
  {
    id: "notifications-5",
    name: "Calendar Reminder",
    description: "A gentle reminder sound for calendar events",
    category: "Notifications",
    tags: ["calendar", "reminder", "event", "gentle", "schedule"],
    duration: 0.4,
    audioUrl: "/sounds/Notification_5.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-08-25",
    featured: false,
    downloads: 1987,
  },
  {
    id: "notifications-6",
    name: "Task Complete",
    description: "A satisfying sound for completed tasks",
    category: "Notifications",
    tags: ["task", "complete", "satisfying", "done", "achievement"],
    duration: 0.4,
    audioUrl: "/sounds/Notification_6.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-09-05",
    featured: false,
    downloads: 3456,
  },
  {
    id: "notifications-7",
    name: "Message Alert",
    description: "A friendly notification for new messages",
    category: "Notifications",
    tags: ["message", "alert", "friendly", "chat", "communication"],
    duration: 0.4,
    audioUrl: "/sounds/Notification_7.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-10-15",
    featured: false,
    downloads: 2987,
  },
  {
    id: "notifications-8",
    name: "App Update",
    description: "A modern notification for app updates",
    category: "Notifications",
    tags: ["app", "update", "modern", "notification", "software"],
    duration: 0.4,
    audioUrl: "/sounds/Notification_8.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-11-25",
    featured: false,
    downloads: 2765,
  },
  {
    id: "pop-1",
    name: "Bubble Pop",
    description: "A playful bubble popping sound effect",
    category: "Pop",
    tags: ["bubble", "pop", "playful", "fun", "light"],
    duration: 0.4,
    audioUrl: "/sounds/Pop_1.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-04-15",
    featured: false,
    downloads: 3456,
  },
  {
    id: "pop-2",
    name: "Balloon Pop",
    description: "A satisfying balloon popping sound",
    category: "Pop",
    tags: ["balloon", "pop", "satisfying", "party", "celebration"],
    duration: 0.4,
    audioUrl: "/sounds/Pop_2.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-05-25",
    featured: false,
    downloads: 2987,
  },
  {
    id: "pop-3",
    name: "Cork Pop",
    description: "A celebratory champagne cork popping sound",
    category: "Pop",
    tags: ["cork", "champagne", "celebration", "party", "pop"],
    duration: 0.4,
    audioUrl: "/sounds/Pop_3.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-06-20",
    featured: false,
    downloads: 2765,
  },
  {
    id: "pop-4",
    name: "Soap Bubble",
    description: "A delicate soap bubble popping sound",
    category: "Pop",
    tags: ["soap", "bubble", "delicate", "gentle", "pop"],
    duration: 0.4,
    audioUrl: "/sounds/Pop_4.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-07-30",
    featured: false,
    downloads: 1987,
  },
  {
    id: "pop-5",
    name: "Plastic Pop",
    description: "A crisp plastic bubble wrap popping sound",
    category: "Pop",
    tags: ["plastic", "bubble", "wrap", "crisp", "pop"],
    duration: 0.4,
    audioUrl: "/sounds/Pop_5.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-08-10",
    featured: false,
    downloads: 3456,
  },
  {
    id: "pop-6",
    name: "Water Drop",
    description: "A clear water drop popping sound",
    category: "Pop",
    tags: ["water", "drop", "clear", "liquid", "pop"],
    duration: 0.4,
    audioUrl: "/sounds/Pop_6.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-09-15",
    featured: false,
    downloads: 2987,
  },
  {
    id: "pop-7",
    name: "Firework Pop",
    description: "A festive firework popping sound",
    category: "Pop",
    tags: ["firework", "pop", "festive", "celebration", "party"],
    duration: 0.4,
    audioUrl: "/sounds/Pop_7.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-10-20",
    featured: false,
    downloads: 4321,
  },
  {
    id: "pop-8",
    name: "Bubble Wrap",
    description: "A satisfying bubble wrap popping sequence",
    category: "Pop",
    tags: ["bubble", "wrap", "satisfying", "sequence", "pop"],
    duration: 0.4,
    audioUrl: "/sounds/Pop_8.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2025-11-30",
    featured: false,
    downloads: 2765,
  },
  {
    id: "alert-1",
    name: "Alert",
    description: "Subtle sound for loading interactions",
    category: "Alert",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Alert_1.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "alert-2",
    name: "Alert",
    description: "Subtle sound for loading interactions",
    category: "Alert",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Alert_2.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "alert-3",
    name: "Alert",
    description: "Subtle sound for loading interactions",
    category: "Alert",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Alert_3.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "alert-4",
    name: "Alert",
    description: "Subtle sound for loading interactions",
    category: "Alert",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Alert_4.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "transitions-1",
    name: "Transition",
    description: "Subtle sound for loading interactions",
    category: "Transitions",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Transition_1.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "transitions-2",
    name: "Transition",
    description: "Subtle sound for loading interactions",
    category: "Transitions",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Transition_2.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "transitions-3",
    name: "Transition",
    description: "Subtle sound for loading interactions",
    category: "Transitions",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Transition_3.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "transitions-4",
    name: "Transition",
    description: "Subtle sound for loading interactions",
    category: "Transitions",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Transition_4.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "typing-1",
    name: "Typing",
    description: "Subtle sound for loading interactions",
    category: "Typing",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Typing_1.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "typing-2",
    name: "Typing",
    description: "Subtle sound for loading interactions",
    category: "Typing",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Typing_2.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "typing-3",
    name: "Typing",
    description: "Subtle sound for loading interactions",
    category: "Typing",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Typing_3.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "typing-4",
    name: "Typing",
    description: "Subtle sound for loading interactions",
    category: "Typing",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Typing_4.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "typing-5",
    name: "Typing",
    description: "Subtle sound for loading interactions",
    category: "Typing",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Typing_5.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "typing-6",
    name: "Typing",
    description: "Subtle sound for loading interactions",
    category: "Typing",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Typing_6.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "typing-7",
    name: "Typing",
    description: "Subtle sound for loading interactions",
    category: "Typing",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Typing_7.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "typing-8",
    name: "Typing",
    description: "Subtle sound for loading interactions",
    category: "Typing",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Typing_8.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "navigation-1",
    name: "Navigation",
    description: "Subtle sound for loading interactions",
    category: "Navigation",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Navigation_1.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "navigation-2",
    name: "Navigation",
    description: "Subtle sound for loading interactions",
    category: "Navigation",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Navigation_2.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "navigation-3",
    name: "Navigation",
    description: "Subtle sound for loading interactions",
    category: "Navigation",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Navigation_3.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
  {
    id: "navigation-4",
    name: "Navigation",
    description: "Subtle sound for loading interactions",
    category: "Navigation",
    tags: ["loading", "interface", "subtle", "UI"],
    duration: 0.4,
    audioUrl: "/sounds/Navigation_4.mp3",
    waveform: [0.3, 0.5, 0.3, 0.1],
    createdAt: "2023-02-20",
    featured: false,
    downloads: 412,
  },
];
